version: "3"

services:
    allure:
        image: frankescobar/allure-docker-service
        environment:
          CHECK_RESULTS_EVERY_SECONDS: 5
        ports:
          - "4040:4040"
          - "5050:5050"
        volumes:
          - ./allure-results:/app/allure-results
          - ./allure-report:/app/allure-report