version: "3"

services:
    test_runner:
        build: .
        image: rest-api/pytest_runner
        container_name: pytest_runner_works
        environment: 
            - ENV=dev
        volumes: 
            - .:/tests_project/
